namespace Eudaimonia.Domain;

public enum Genre
{
    Action = 1,
    Adventure,
    Classic,
    Contemporary,
    Dystopian,
    Fantasy,
    GraphicNovel,
    Historical,
    Horror,
    Mystery,
    Romance,
    Satire,
    ScienceFiction,
    ShortStory,
    Thriller,
    Utopian,
    Western,
    ArtAndPhotography,
    Biography,
    Cookbooks,
    HowtoandDIY,
    Humor,
    Parenting,
    Autobiography,
    Philosophy,
    Religion,
    Spirituality,
    SelfHelp,
    Travel,
    TrueCrime,
}